### ISSUE TITLE
Excessive API calls

### ISSUE THREAD

**Issue by pgib** [boltops-tools/serverlessgems#6]
I'm having a challenging time getting a small, personal project going because each time I try to deploy to test a change, calls are going out to the Serverless Gems API unnecessarily (i.e. I'm not making any changes to my gems, and local copies exist of every gem I need from the first deployment). Setting `Jets.config.gems.disable = true` seems to have other side effects, and I so far haven't had luck cloning the Lambda gem layer and explicitly using that instead.

I get the API limits for downloading files, but it seems that if there's not a way to cache the information locally and then only make calls to check if the gem exists if it's not been checked before, then perhaps the API limits could apply to downloads only. From what I can see, it won't download the files if they have already been downloaded, but it doesn't get an opportunity to do that.

**Comment by tongueroo** [comment]
To be upfront, open source has been pretty tricky to try to support. Trying this as the business model. Closing out
